CREATE DATABASE IF NOT EXISTS Wallet;

USE Wallet;

CREATE TABLE IF NOT EXISTS users
(
    user_id  INT PRIMARY KEY AUTO_INCREMENT,
    email    VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL
)
